# Site settings
title: Brad Pitcher
email: bradpitcher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Passion for creating things and learning are what drives me in life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brad.github.io" # the base hostname & protocol for your site
twitter_username: bradpitcher
github_username:  brad

# Build settings
markdown: kramdown

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
